version: '3.7'
services:
    frontend:
        build: .
        command: npm run dev
        volumes:
            - .:/code
        ports:
            - "8080:8080"
networks:
    default:
        external:
            name: quantum_web
